name: MChannels
main: com.miraclem4n.mchannels.MChannels
version: ${m.version}-${build.number}-${p.version}
author: MiracleM4n
authors: [MiracleM4n]
website: http://mdev.in/
softdepend: [mChatSuite, MChat]
description: PM funcionatily, Shout, Mute, etc.
commands:
    msocial:
        aliases: [msoc, ms]
permissions:
    msocial.*:
        default: op
        description: Allows full use of MSocial.
        children:
            msocial.reload: true
    msocial.reload:
        default: false
        description: Allow usage of /msocial reload command.
